/// Flutter icons GIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  GIcons
///      fonts:
///       - asset: fonts/GIcons.ttf
///
/// 
/// * Octicons, Copyright (C) 2020 by GitHub Inc.
///         Author:    GitHub
///         License:   MIT (http://opensource.org/licenses/mit-license.php)
///         Homepage:  https://primer.style/octicons/
///
import 'package:flutter/widgets.dart';

class GIcons {
  GIcons._();

  static const _kFontFam = 'GIcons';
  static const _kFontPkg = null;

  static const IconData primitive_dot = IconData(0xf30c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
